name: challenge_crypto_tracker_lite
description: "challenge for a apply position front end puul"

version: 1.0.0+1

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  freezed_annotation: ^3.1.0
  go_router: ^17.0.0
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.3
  fl_chart: ^1.1.1
  json_annotation: ^4.9.0
  dio: ^5.9.0
  get_it: ^9.1.1
  nested: ^1.0.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  freezed: ^3.2.3
  json_serializable: ^6.11.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/
